### PR TITLE
Add 4:3 HD Format support

### PR DESCRIPTION
**Pull request by damysteryman**
- Added support for 1440 x 1080 & 960 x 720 formats
- Added support for parsing WIDTHxHEIGHT VideoFormat string (e.g. "1440x1080") in BDN XML

### CODE REVIEW

**Comment by cubicibo** [comment]
Hi,
Thanks for the PR. I don't think 1440x1080 or 960x720 is allowed by the Blu-ray standard specifications.

Should we pad the output so that it remains centered in 1920x1080 or 1280x720 (Blu-ray standard video format) PGS files? What do you think?

**Comment by damysteryman** [comment]
Ah ok, I did not know that. My use case here was manipulating an .mkv video ripped from a bluray, rather than creating data for one.

Only reason I added in the change was because I was intentionally attempting to crop a .sup from 16:9 to 4:3 (for an .mkv video that had already been cropped) in BDSup2Sub app, and it spat out a bdn xml with ' VideoFormat="1440x1080" ' in the Format tag.
Adding in the 720 4:3 format was just a guess based on the same idea as what BDSup2Sub did with the 1080 4:3 option mentioned above.

So I'm fine with whatever you want to do/not do with these changes.

**Comment by cubicibo** [comment]
The overlaying process of PGS happens at the output of the Blu-ray video decoder output. The later can only output video at 1920x1080, 1280x720, 720x576 or 720x480. So PGS output is bound to the same formats. From the Blu-ray White Paper:
pg_plane_spec

Software players are not bound by the same limitations, but PGS remain an oddball format and is rarely mismatched with a different video. I don't mind adding support for out-of-spec video formats but there must be some extra care taken:

- Properly warn the user when the conversion starts and ends.
- Disable PES+MUI output, or throw an error if the user attempts to output PES+MUI with an illegal video format, as these files are meant to be used in professional authoring setups.
- Probably some other things needs to be addressed.

Furthermore, this `WxH` notation in BDN-XML is non standard too, so I've been told.  I also thought it was allowed at some point but Sony & co. are so secretive on the BD format that it is just one of the many missconception that has found its way in tools over the years...

**Comment by cubicibo** [comment]
Hi, apologies for the delay. I decided to merge only the commit that adds WxH parsing support: aff23c55f43c3601003a83c5103117911f15b943

I think we should prevent the spread of non-conventional/out of spec subtitles, so I chose not to take the other commit. Thank you for your help!

**Pull request closed without merging**
